class Routes {
  Routes._();
  static const String splash = '/splash';
  static const String home = '/home';
  static const String onBoarding = '/onBoarding';
  static const String seeAllPage = '/SeeAllPage';
  static const String tourCity = '/CityToursView';
  static const String countryDetails = '/SingleCountryView';
  static const String setting = '/SittingScreen';
  static const String cityDetailsScreen = '/CityDetailsScreen';
  static const String packageView = '/packageView';
  static const String countriesView = '/countriesView';
  static const String cityTourDetails = '/cityTourDetails';
  static const String hotelDetails = '/hotelDetails';
  static const String packagesListView = '/packagesListView';
  static const String packageDetailsView = '/packageDetailsView';
  static const String languageScreen = '/languageScreen';
  static const String servicesView = '/servicesView';
  static const String aboutUsScreen = '/AboutUsScreen';
  static const String contactInfoView = '/ContactInfoView';
  static const String allCountriesPage = '/AllCountriesPage';
  static const String allToursPage = '/AllToursPage';
  static const String globalSettingsView = '/GlobalSettingsView';
  static const String flightBookingScreen = '/FlightBookingScreen';
  static const String cityPage = '/CityPage';
  static const String cityDetailsPage = '/CityDetailsPage';
  static const String allHotelsPage = '/AllHotelsPage';
  static const String viatorAllToursPage = '/viatorAllToursPage';
  static const String cityGuideDetailsView = '/CityGuideDetailsView';
  static const String termsAndConditions = '/TermsAndConditions';
  static const String privacyPolicy = '/PrivacyPolicy';
}
